import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
       <nav>
        <img />
        <a href='/' >Home</a>
        <a href='events' >Events</a>
        <a href='about-us' >About us</a>
       </nav> 
      </header>
      <main className={styles.main}>
        <h1></h1>
        {data.map(events => {
          return(
            <a key={events.id} href={`/events/${events.id}`}>
              {/* <Image width={200} height={100}  src={events.image}/> */}
              <h2>{events.title}</h2>
              <p>{events.description}</p>
            </a>
          )
        })}
        <a href="/events/london" >
          <img />
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere tincidunt volutpat. Aenean sed pellentesque est. Integer in imperdiet dolor. Vivamus viverra, metus nec facilisis imperdiet, quam mauris tincidunt risus, a facilisis nisl est vel ex. Morbi id tellus eros. Ut ante arcu, hendrerit ac velit id, volutpat interdum tortor. Sed et tempor lorem, et tincidunt tortor. Phasellus lacinia nisi est, eget commodo lacus porttitor ac.</p>
        </a>
        <a href="/events/san-francisco" >
          <img />
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere tincidunt volutpat. Aenean sed pellentesque est. Integer in imperdiet dolor. Vivamus viverra, metus nec facilisis imperdiet, quam mauris tincidunt risus, a facilisis nisl est vel ex. Morbi id tellus eros. Ut ante arcu, hendrerit ac velit id, volutpat interdum tortor. Sed et tempor lorem, et tincidunt tortor. Phasellus lacinia nisi est, eget commodo lacus porttitor ac.</p>
        </a>
        <a href="/events/barcelona" >
          <img />
          <h2>Events in Barcelona</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed posuere tincidunt volutpat. Aenean sed pellentesque est. Integer in imperdiet dolor. Vivamus viverra, metus nec facilisis imperdiet, quam mauris tincidunt risus, a facilisis nisl est vel ex. Morbi id tellus eros. Ut ante arcu, hendrerit ac velit id, volutpat interdum tortor. Sed et tempor lorem, et tincidunt tortor. Phasellus lacinia nisi est, eget commodo lacus porttitor ac.</p>
        </a>
      </main>
      <footer>
        <p>2023 CopyRights</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  
  const {events_categories} = await import('/data/data.json')
  return {
      props: {
          data: events_categories
      }
  }
}
